-- AGGREGATE QUERIES WITH MBA DATA

-- CREATE MBA TABLE
CREATE TABLE MBA(
	DATASRO INT,
	WORKEX INT,
	GMAT INT
);

-- SELECT ALL MBA TABLE
SELECT *FROM MBA;

-- MAX AND MIN WORKEX 
SELECT MAX(WORKEX) FROM MBA;
SELECT MIN(WORKEX) FROM MBA;

-- MAX AND MIN GMAT
SELECT MAX(GMAT) FROM MBA;
SELECT MIN(GMAT) FROM MBA;

-- WORKEX AND GMAT WHERE MAX VALUES
SELECT WORKEX,GMAT FROM MBA WHERE WORKEX = 279;
SELECT WORKEX,GMAT FROM MBA WHERE GMAT = 780;

-- WORKEX HIGHEST TO LOWEST
SELECT DISTINCT WORKEX FROM MBA ORDER BY WORKEX DESC;
-- WORKEX LOWEST TO HIGHEST
SELECT DISTINCT WORKEX FROM MBA ORDER BY WORKEX;

-- GMAT HIGHEST TO LOWEST
SELECT DISTINCT GMAT FROM MBA ORDER BY GMAT DESC;
-- GMAT LOWEST TO HIGHEST
SELECT DISTINCT GMAT FROM MBA ORDER BY GMAT;

-- WORKEX TOP 5 AND TOP 3
SELECT DISTINCT WORKEX FROM MBA ORDER BY WORKEX DESC LIMIT 5;
SELECT DISTINCT WORKEX FROM MBA ORDER BY WORKEX DESC LIMIT 3;
-- GMAT TOP 5 AND TOP 3
SELECT DISTINCT GMAT FROM MBA ORDER BY GMAT DESC LIMIT 5;
SELECT DISTINCT GMAT FROM MBA ORDER BY GMAT DESC LIMIT 3;

-- MBA TABLE SORTED BY HIGHEST WORKEX AND GMAT SCORES
SELECT * FROM MBA ORDER BY WORKEX DESC, GMAT DESC;

-- START TO ORDER TABLE AFTER 2ND ROW
SELECT WORKEX,GMAT FROM MBA ORDER BY GMAT LIMIT 5 OFFSET 2;

-- FILTER WORKEX GREATER THAN 150
SELECT WORKEX FROM MBA WHERE WORKEX > 150 ORDER BY WORKEX DESC;

-- FILTER GMAT GREATER THAN 600
SELECT GMAT FROM MBA WHERE GMAT > 600 ORDER BY GMAT DESC;

-- SUM OF WORKEX AND GMAT
SELECT SUM(WORKEX),SUM(GMAT) FROM MBA;

-- AVG OF WORKEX AND GMAT
SELECT AVG(WORKEX) AS AVG_WORKEX,AVG(GMAT) AS AVG_GMAT FROM MBA;




